// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple_enum.proto

package simple_enum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SomeEnum int32

const (
	SomeEnum_ONE   SomeEnum = 0
	SomeEnum_TWO   SomeEnum = 1
	SomeEnum_THREE SomeEnum = 2
)

var SomeEnum_name = map[int32]string{
	0: "ONE",
	1: "TWO",
	2: "THREE",
}

var SomeEnum_value = map[string]int32{
	"ONE":   0,
	"TWO":   1,
	"THREE": 2,
}

func (x SomeEnum) String() string {
	return proto.EnumName(SomeEnum_name, int32(x))
}

func (SomeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_adc04066f2391555, []int{0}
}

type SomeMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	E                    SomeEnum `protobuf:"varint,2,opt,name=e,proto3,enum=simple.enum.SomeEnum" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SomeMessage) Reset()         { *m = SomeMessage{} }
func (m *SomeMessage) String() string { return proto.CompactTextString(m) }
func (*SomeMessage) ProtoMessage()    {}
func (*SomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc04066f2391555, []int{0}
}

func (m *SomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeMessage.Unmarshal(m, b)
}
func (m *SomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeMessage.Marshal(b, m, deterministic)
}
func (m *SomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeMessage.Merge(m, src)
}
func (m *SomeMessage) XXX_Size() int {
	return xxx_messageInfo_SomeMessage.Size(m)
}
func (m *SomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SomeMessage proto.InternalMessageInfo

func (m *SomeMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SomeMessage) GetE() SomeEnum {
	if m != nil {
		return m.E
	}
	return SomeEnum_ONE
}

func init() {
	proto.RegisterEnum("simple.enum.SomeEnum", SomeEnum_name, SomeEnum_value)
	proto.RegisterType((*SomeMessage)(nil), "simple.enum.SomeMessage")
}

func init() { proto.RegisterFile("simple_enum.proto", fileDescriptor_adc04066f2391555) }

var fileDescriptor_adc04066f2391555 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xce, 0xcc, 0x2d,
	0xc8, 0x49, 0x8d, 0x4f, 0xcd, 0x2b, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86,
	0x08, 0xe9, 0x81, 0x84, 0x94, 0x9c, 0xb8, 0xb8, 0x83, 0xf3, 0x73, 0x53, 0x7d, 0x53, 0x8b, 0x8b,
	0x13, 0xd3, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83,
	0x98, 0x32, 0x53, 0x84, 0x94, 0xb9, 0x18, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x44,
	0xf5, 0x90, 0xf4, 0xe9, 0x81, 0x34, 0xb9, 0xe6, 0x95, 0xe6, 0x06, 0x31, 0xa6, 0x6a, 0xa9, 0x73,
	0x71, 0xc0, 0xb8, 0x42, 0xec, 0x5c, 0xcc, 0xfe, 0x7e, 0xae, 0x02, 0x0c, 0x20, 0x46, 0x48, 0xb8,
	0xbf, 0x00, 0xa3, 0x10, 0x27, 0x17, 0x6b, 0x88, 0x47, 0x90, 0xab, 0xab, 0x00, 0x53, 0x12, 0x1b,
	0xd8, 0x01, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xac, 0xb5, 0x25, 0x95, 0x00, 0x00,
	0x00,
}
